name: Unit and Functional Testing

on: [push, pull_request]
env: # Or as an environment variable
  GITPASS_REPO_MODULOS: ${{ secrets.GITPASS_REPO_MODULOS }}
  GITUSER_REPO_MODULOS: ${{ secrets.GITUSER_REPO_MODULOS }}
  ENVTEST: 'teste de env'
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Fetch Pull Request branch
        uses: actions/checkout@v3
      - name: Run make tests containers
        run: echo "Olá $GITUSER_REPO_MODULOS  - $ENVTEST" ; cd containers/tests; make getenv-test; make test-containers
