name: Unit and Functional Testing

on: [push, pull_request]
env: # Or as an environment variable
  GITPASS_REPO_MODULOS: ${{ secrets.GITPASSREPOMODULOS }}
  GITUSER_REPO_MODULOS: ${{ secrets.GITUSERREPOMODULOS }}
  SUPER_PATH: /home/runner/work/super-docker/super-docker/super/src
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Fetch Pull Request branch
        uses: actions/checkout@v3
      - name: Run make tests containers
        run: cd containers/tests; make getenv-test; make test-containers; cd ../../
      - name: Fetch código do SUPER
        uses: actions/checkout@v3
        with:
            repository: supergovbr/super
            token: ${{ secrets.GH_PAT }}
            path: super
      - name: Run make tests app
        run: pwd; cd dev/tests; make tests-all-bases; cd ../../
