name: Unit and Functional Testing

on: [push, pull_request]
env: # Or as an environment variable
  GITPASS_REPO_MODULOS: ${{ secrets.GITPASSREPOMODULOS }}
  GITUSER_REPO_MODULOS: ${{ secrets.GITUSERREPOMODULOS }}
  ENVTEST: 'teste de env'
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Fetch Pull Request branch
        uses: actions/checkout@v3
      - name: Run make tests containers
        run: cd containers/tests; make getenv-test; make test-containers
